# Generated by Django 4.1.1 on 2022-09-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_project_service_alter_service_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Image',
            new_name='image',
        ),
    ]
